<a href="https://colab.research.google.com/github/nisha1365/Sanofi-POC/blob/main/Merging_all_Data_Frames.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 1st CSV "Tweet hemophilia alldata db 17_08_23".

In [1]:
import pandas as pd

In [4]:
df1 = pd.read_csv("/content/tweet_hemophilia_alldata_db_17_08_23.csv")
df1

,Unnamed: 0,tweet_id,external_twitter_id,text,author_id,created_at,lang,referenced_tweets_type,referenced_tweets_id,infos,association_tweet_id,association_scope_id
0,0,1030258,1684840696631422976,3 peaks Challenge #AxioActive💪\n\nOn the 12th ...,905089209446346752,2023-07-28 08:18:19,en,0,0,{},1030258,10
1,1,1030186,1684592270652452864,"Roche Drops Hemophilia A Candidate, Prepares f...",76385834,2023-07-27 15:51:10,en,0,0,{},1030186,10
2,2,1030263,1684814677086187520,Roche moves one Spark hemophilia gene therapy ...,1481278019352338433,2023-07-28 06:34:56,en,0,0,{},1030263,10
3,3,1030274,1684722157685993472,On #WorldHepatitisDay we put middle finger up ...,1145266586015502336,2023-07-28 00:27:17,en,0,0,{},1030274,10
4,4,1030288,1684658401794469888,"One of our newest internship programs, launche...",211288748,2023-07-27 20:13:57,en,3,1684634783865843712,{},1030288,10
...,...,...,...,...,...,...,...,...,...,...,...,...
15461,15461,170058,1623060615991291927,Are you planning to attend college or technica...,486760024,2023-02-07 20:46:20,en,0,0,{},170058,10
15462,15462,170507,1623692536354070529,Excited to see ATHN 7 research displayed at th...,1365289018607419398,2023-02-09 14:37:22,en,0,0,{},170507,10
15463,15463,170966,1625648406721880068,The latest The Daily Bleeder! https://t.co/Gmb...,62750890,2023-02-15 00:09:17,en,0,0,{},170966,10
15464,15464,171494,1628077094440943616,"Emicizumab (Hemlibra) Appears Safe, Effective ...",2510959423,2023-02-21 17:00:02,en,0,0,{},171494,10
15465,15465,172062,1630292933139202050,@aizaispiral I need him so bad also I think ha...,1261861179045052418,2023-02-27 19:44:59,en,2,1630186552948129793,{},172062,10

In [8]:
df1.drop(['Unnamed: 0'], axis = 1, inplace = True)
df1.head()

,tweet_id,external_twitter_id,text,author_id,created_at,lang,referenced_tweets_type,referenced_tweets_id,infos,association_tweet_id,association_scope_id
0,1030258,1684840696631422976,3 peaks Challenge #AxioActive💪\n\nOn the 12th ...,905089209446346752,2023-07-28 08:18:19,en,0,0,{},1030258,10
1,1030186,1684592270652452864,"Roche Drops Hemophilia A Candidate, Prepares f...",76385834,2023-07-27 15:51:10,en,0,0,{},1030186,10
2,1030263,1684814677086187520,Roche moves one Spark hemophilia gene therapy ...,1481278019352338433,2023-07-28 06:34:56,en,0,0,{},1030263,10
3,1030274,1684722157685993472,On #WorldHepatitisDay we put middle finger up ...,1145266586015502336,2023-07-28 00:27:17,en,0,0,{},1030274,10
4,1030288,1684658401794469888,"One of our newest internship programs, launche...",211288748,2023-07-27 20:13:57,en,3,1684634783865843712,{},1030288,10

In [9]:
df1['tweet_id'].nunique()

15466

In [5]:
df2 = pd.read_csv("/content/tweet_hemophilia_alldata_db.csv")
df2

,Unnamed: 0,tweet_id,text,author_id,created_at,lang,referenced_tweets_type,referenced_tweets_id,infos,association_tweet_id,association_scope_id
0,0,1638511061652455425,They say old age isn't so bad when considering...,303118729,2023-03-22 12:00:53,en,0,0,{},1638511061652455425,10
1,1,1638688071012032513,If by AMD you mean Age-related Macular Degener...,84063737,2023-03-22 23:44:16,en,3,1638684815720366080,{},1638688071012032513,10
2,2,1638851084696563712,🗒️ How can your institution prepare to offer g...,33633067,2023-03-23 10:32:01,en,0,0,{},1638851084696563712,10
3,3,1638518390359834624,Hemophilia is an inherited disorder in which t...,1044251825921241088,2023-03-22 12:30:01,en,0,0,{},1638518390359834624,10
4,4,1638682916212359169,Time for a condemnation\n@wfhemophilia @isth @...,2317618712,2023-03-22 23:23:47,en,3,1638583428688879621,{},1638682916212359169,10
...,...,...,...,...,...,...,...,...,...,...,...
14332,14332,1683839551645814784,"Hear more from Mosi Williams, Pys.D, on the la...",1479181194516381700,2023-07-25 14:00:07,en,0,0,{},1683839551645814784,10
14333,14333,1683938283003183104,"Was discussing hemophilia with an intelligent,...",276085643,2023-07-25 20:32:27,en,0,0,{},1683938283003183104,10
14334,14334,1683861079674195968,The affected &amp; infected have waited decade...,110418098,2023-07-25 15:25:40,en,3,1683849423619518464,{},1683861079674195968,10
14335,14335,1683918306082955264,"@MohmdBio Sickle cell anemia, Thalassemia, Hem...",1179872500269932544,2023-07-25 19:13:04,en,2,1683917518220451855,{},1683918306082955264,10
14336,14336,1683834001562140672,Save the date to “tee up for a cure” on Monday...,486760024,2023-07-25 13:38:04,en,0,0,{},1683834001562140672,10

In [7]:
df2['tweet_id'].nunique()

14337

In [10]:
df2.drop(['Unnamed: 0'], axis = 1, inplace = True)
df2.head()

,tweet_id,text,author_id,created_at,lang,referenced_tweets_type,referenced_tweets_id,infos,association_tweet_id,association_scope_id
0,1638511061652455425,They say old age isn't so bad when considering...,303118729,2023-03-22 12:00:53,en,0,0,{},1638511061652455425,10
1,1638688071012032513,If by AMD you mean Age-related Macular Degener...,84063737,2023-03-22 23:44:16,en,3,1638684815720366080,{},1638688071012032513,10
2,1638851084696563712,🗒️ How can your institution prepare to offer g...,33633067,2023-03-23 10:32:01,en,0,0,{},1638851084696563712,10
3,1638518390359834624,Hemophilia is an inherited disorder in which t...,1044251825921241088,2023-03-22 12:30:01,en,0,0,{},1638518390359834624,10
4,1638682916212359169,Time for a condemnation\n@wfhemophilia @isth @...,2317618712,2023-03-22 23:23:47,en,3,1638583428688879621,{},1638682916212359169,10

In [13]:
common_tweetids = set(df1['tweet_id']).intersection(set(df2['tweet_id']))

if common_tweetids:
  print(f"Commontweetids found: {common_tweetids}")

else:
  print("No common tweetids found.")

No common tweetids found.

No common tweets, so using Concatenation function not merging.

In [14]:
combined_df = pd.concat([df1,df2], ignore_index=True)
combined_df

,tweet_id,external_twitter_id,text,author_id,created_at,lang,referenced_tweets_type,referenced_tweets_id,infos,association_tweet_id,association_scope_id
0,1030258,1.684841e+18,3 peaks Challenge #AxioActive💪\n\nOn the 12th ...,905089209446346752,2023-07-28 08:18:19,en,0,0,{},1030258,10
1,1030186,1.684592e+18,"Roche Drops Hemophilia A Candidate, Prepares f...",76385834,2023-07-27 15:51:10,en,0,0,{},1030186,10
2,1030263,1.684815e+18,Roche moves one Spark hemophilia gene therapy ...,1481278019352338433,2023-07-28 06:34:56,en,0,0,{},1030263,10
3,1030274,1.684722e+18,On #WorldHepatitisDay we put middle finger up ...,1145266586015502336,2023-07-28 00:27:17,en,0,0,{},1030274,10
4,1030288,1.684658e+18,"One of our newest internship programs, launche...",211288748,2023-07-27 20:13:57,en,3,1684634783865843712,{},1030288,10
...,...,...,...,...,...,...,...,...,...,...,...
29798,1683839551645814784,NaN,"Hear more from Mosi Williams, Pys.D, on the la...",1479181194516381700,2023-07-25 14:00:07,en,0,0,{},1683839551645814784,10
29799,1683938283003183104,NaN,"Was discussing hemophilia with an intelligent,...",276085643,2023-07-25 20:32:27,en,0,0,{},1683938283003183104,10
29800,1683861079674195968,NaN,The affected &amp; infected have waited decade...,110418098,2023-07-25 15:25:40,en,3,1683849423619518464,{},1683861079674195968,10
29801,1683918306082955264,NaN,"@MohmdBio Sickle cell anemia, Thalassemia, Hem...",1179872500269932544,2023-07-25 19:13:04,en,2,1683917518220451855,{},1683918306082955264,10
29802,1683834001562140672,NaN,Save the date to “tee up for a cure” on Monday...,486760024,2023-07-25 13:38:04,en,0,0,{},1683834001562140672,10

In [15]:
combined_df.isnull().sum()

tweet_id                      0
external_twitter_id       14337
text                          0
author_id                     0
created_at                    0
lang                          0
referenced_tweets_type        0
referenced_tweets_id          0
infos                         0
association_tweet_id          0
association_scope_id          0
dtype: int64

In [16]:
df3 = pd.read_csv('/content/list_of_likes_by_tweet_id_050423.csv')
df3

,Unnamed: 0,tweet_id,list_of_likes,date_of_collect,count_likes
0,0,1632975716743512066,[],2023-04-05 17:25:37,0
1,1,1632259786216464384,[],2023-04-05 17:25:37,0
2,2,1621748658461937668,"[{'id': '2891104408', 'name': 'Courtney Thornb...",2023-04-05 17:25:37,3
3,3,1638052976718741507,[],2023-04-05 17:25:38,0
4,4,1638778233221988353,"[{'id': '324737377', 'name': 'Rob Fishbeck', '...",2023-04-05 17:25:38,5
5,5,1619199920568942592,[],2023-04-05 17:25:38,0
6,6,1623924825730211841,"[{'id': '75264181', 'name': 'Zaragoza', 'usern...",2023-04-05 17:25:38,3
7,7,1636968941544435717,"[{'id': '2741572224', 'name': 'Mohammad Rafeeq...",2023-04-05 17:25:39,3
8,8,1634794789496406016,[],2023-04-05 17:25:39,0
9,9,1617034096471080961,[],2023-04-05 17:25:39,0
10,10,1627911069711667201,"[{'id': '75264181', 'name': 'Zaragoza', 'usern...",2023-04-05 17:25:40,8
11,11,1628263029447225344,"[{'id': '27359147', 'name': 'JanS65', 'usernam...",2023-04-05 17:25:40,5
12,12,1623200119439908864,"[{'id': '1534906706425221120', 'name': 'Kaye B...",2023-04-05 17:25:41,4
13,13,1630446619685539842,"[{'id': '1260888554307190784', 'name': ""Haemop...",2023-04-05 17:25:41,3
14,14,1637331834190331904,[],2023-04-05 17:25:41,0
15,15,1639143033081073664,[],2023-04-05 17:25:42,0
16,16,1624286621008027648,[],2023-04-05 17:25:42,0
17,17,1630807381490933765,"[{'id': '1572133296108367878', 'name': 'Abhika...",2023-04-05 17:25:43,4
18,18,1625736735648022528,[],2023-04-05 17:25:43,0
19,19,1633699654629224449,"[{'id': '1476068819655270402', 'name': 'Longdo...",2023-04-05 17:25:44,9
20,20,1635521093174738946,"[{'id': '1602716642848690176', 'name': 'Louise...",2023-04-05 17:25:44,2
21,21,1626456583952646152,"[{'id': '947141071242440705', 'name': 'David',...",2023-04-05 17:25:44,2
22,22,1626822592119046145,"[{'id': '20508021', 'name': 'Heather Mason', '...",2023-04-05 17:25:45,2

In [17]:
df3.drop(['Unnamed: 0'], axis = 1, inplace = True)
df3.head()

,tweet_id,list_of_likes,date_of_collect,count_likes
0,1632975716743512066,[],2023-04-05 17:25:37,0
1,1632259786216464384,[],2023-04-05 17:25:37,0
2,1621748658461937668,"[{'id': '2891104408', 'name': 'Courtney Thornb...",2023-04-05 17:25:37,3
3,1638052976718741507,[],2023-04-05 17:25:38,0
4,1638778233221988353,"[{'id': '324737377', 'name': 'Rob Fishbeck', '...",2023-04-05 17:25:38,5

In [18]:
common_tweetids = set(combined_df['tweet_id']).intersection(set(df3['tweet_id']))

if common_tweetids:
  print(f"Commontweetids found: {common_tweetids}")

else:
  print("No common tweetids found.")

Commontweetids found: {1632259786216464384, 1638778233221988353, 1632975716743512066, 1638052976718741507, 1621748658461937668, 1619199920568942592, 1623924825730211841, 1636968941544435717, 1634794789496406016, 1617034096471080961, 1627911069711667201, 1630446619685539842, 1630807381490933765, 1633699654629224449, 1635521093174738946, 1626456583952646152, 1623200119439908864, 1624286621008027648, 1626822592119046145, 1628263029447225344, 1637331834190331904, 1625736735648022528, 1639143033081073664}

In [19]:
combined_df1 = pd.merge(combined_df, df3, on = 'tweet_id', how = 'outer')
combined_df1

,tweet_id,external_twitter_id,text,author_id,created_at,lang,referenced_tweets_type,referenced_tweets_id,infos,association_tweet_id,association_scope_id,list_of_likes,date_of_collect,count_likes
0,1030258,1.684841e+18,3 peaks Challenge #AxioActive💪\n\nOn the 12th ...,905089209446346752,2023-07-28 08:18:19,en,0,0,{},1030258,10,NaN,NaN,NaN
1,1030186,1.684592e+18,"Roche Drops Hemophilia A Candidate, Prepares f...",76385834,2023-07-27 15:51:10,en,0,0,{},1030186,10,NaN,NaN,NaN
2,1030263,1.684815e+18,Roche moves one Spark hemophilia gene therapy ...,1481278019352338433,2023-07-28 06:34:56,en,0,0,{},1030263,10,NaN,NaN,NaN
3,1030274,1.684722e+18,On #WorldHepatitisDay we put middle finger up ...,1145266586015502336,2023-07-28 00:27:17,en,0,0,{},1030274,10,NaN,NaN,NaN
4,1030288,1.684658e+18,"One of our newest internship programs, launche...",211288748,2023-07-27 20:13:57,en,3,1684634783865843712,{},1030288,10,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29798,1683839551645814784,NaN,"Hear more from Mosi Williams, Pys.D, on the la...",1479181194516381700,2023-07-25 14:00:07,en,0,0,{},1683839551645814784,10,NaN,NaN,NaN
29799,1683938283003183104,NaN,"Was discussing hemophilia with an intelligent,...",276085643,2023-07-25 20:32:27,en,0,0,{},1683938283003183104,10,NaN,NaN,NaN
29800,1683861079674195968,NaN,The affected &amp; infected have waited decade...,110418098,2023-07-25 15:25:40,en,3,1683849423619518464,{},1683861079674195968,10,NaN,NaN,NaN
29801,1683918306082955264,NaN,"@MohmdBio Sickle cell anemia, Thalassemia, Hem...",1179872500269932544,2023-07-25 19:13:04,en,2,1683917518220451855,{},1683918306082955264,10,NaN,NaN,NaN
29802,1683834001562140672,NaN,Save the date to “tee up for a cure” on Monday...,486760024,2023-07-25 13:38:04,en,0,0,{},1683834001562140672,10,NaN,NaN,NaN

In [20]:
df4 = pd.read_csv("/content/authors_info_followers_050423.csv")
df4

,Unnamed: 0.1,Unnamed: 0,author_id,author_info,list_of_followers,date_of_collect,count_followers
0,0,0,1529772772896956417,"{'id': '1529772772896956417', 'name': 'Cures',...","[{'id': '1631787275284631553', 'name': 'Ceceli...",2023-04-05 13:21:44,438
1,1,1,142801414,"{'id': '142801414', 'name': 'NewWayHerbs.com',...","[{'id': '4899374805', 'name': 'orpheus james'...",2023-04-05 13:21:44,978
2,2,2,39823988,"{'id': '39823988', 'name': 'National Hemophili...","[{'id': '1643383029467869188', 'name': 'Sue Ma...",2023-04-05 13:27:41,7184
3,3,3,1638052926487756801,"{'id': '1638052926487756801', 'name': 'Judy Ho...",[],2023-04-05 13:27:41,0
4,4,4,57557894,"{'id': '57557894', 'name': 'Garth Harkness McM...","[{'id': '1537335588583788544', 'name': 'Carol'...",2023-04-05 13:27:42,381
5,5,5,1252986246772559873,"{'id': '1252986246772559873', 'name': 'ingenti...","[{'id': '348598664', 'name': 'R', 'username': ...",2023-04-05 13:27:42,34
6,6,7,120400349,"{'id': '120400349', 'name': 'Javed Ahmad Tak',...","[{'id': '2534529328', 'name': 'ankur singh', '...",2023-04-05 13:27:49,847
7,7,8,994242738676789249,"{'id': '994242738676789249', 'name': 'World Ne...","[{'id': '1498550977820966914', 'name': 'Ayyapp...",2023-04-05 13:42:42,2562
8,8,9,138418838,"{'id': '138418838', 'name': 'Stigmabase | ORG'...","[{'id': '976948534053343233', 'name': 'Andre D...",2023-04-05 13:42:45,4145
9,9,10,1145266586015502336,"{'id': '1145266586015502336', 'name': 'Infecte...","[{'id': '1250020285', 'name': 'gianfra vecchio...",2023-04-05 13:42:46,921
10,10,11,132710839,"{'id': '132710839', 'name': 'Simon Fletcher', ...","[{'id': '1529696540880683009', 'name': 'PopIdl...",2023-04-05 13:42:47,508
11,11,13,843758096250036224,"{'id': '843758096250036224', 'name': 'NYZ News...","[{'id': '1366054148802772992', 'name': 'salva'...",2023-04-05 13:57:43,59
12,12,0,1595547432204410880,{},[],2023-04-05 14:27:44,0
13,13,1,1407146606323900418,"({'id': '1407146606323900418', 'name': 'Vikas ...","[{'id': '1440678523346116609', 'name': '🚩 MANO...",2023-04-05 14:27:48,6051
14,14,2,1530971264613072897,"({'id': '1530971264613072897', 'name': 'tedium...","[{'id': '1409300330358136834', 'name': '𓆨', 'u...",2023-04-05 14:27:48,23
15,15,3,1476068819655270402,"({'id': '1476068819655270402', 'name': 'Longdo...","[{'id': '2257558088', 'name': 'Atanas G. Atana...",2023-04-05 14:27:49,132
16,16,4,1602716642848690176,"({'id': '1602716642848690176', 'name': 'Louise...","[{'id': '2281916715', 'name': '𝑀𝒾𝒸𝓇𝑜𝒷𝒾𝑜𝓁𝑜𝑔𝒾𝓈𝓉 ...",2023-04-05 14:27:49,28
17,17,5,1176211661377683460,"({'id': '1176211661377683460', 'name': 'Malta ...","[{'id': '3782863666', 'name': 'Aggie Mavis Kis...",2023-04-05 14:27:50,35
18,18,0,32054188,"({'id': '32054188', 'name': 'CSL Behring', 'us...","[{'id': '930100881860767744', 'name': 'Sanofi ...",2023-04-05 14:42:50,9723
19,19,1,30846824,"({'id': '30846824', 'name': 'TOI Cities', 'use...","[{'id': '1509988203259785216', 'name': 'Sarpan...",2023-04-05 15:12:51,27862

In [21]:
df4.drop(['Unnamed: 0.1', 'Unnamed: 0'], axis=1, inplace=True)
df4

,author_id,author_info,list_of_followers,date_of_collect,count_followers
0,1529772772896956417,"{'id': '1529772772896956417', 'name': 'Cures',...","[{'id': '1631787275284631553', 'name': 'Ceceli...",2023-04-05 13:21:44,438
1,142801414,"{'id': '142801414', 'name': 'NewWayHerbs.com',...","[{'id': '4899374805', 'name': 'orpheus james'...",2023-04-05 13:21:44,978
2,39823988,"{'id': '39823988', 'name': 'National Hemophili...","[{'id': '1643383029467869188', 'name': 'Sue Ma...",2023-04-05 13:27:41,7184
3,1638052926487756801,"{'id': '1638052926487756801', 'name': 'Judy Ho...",[],2023-04-05 13:27:41,0
4,57557894,"{'id': '57557894', 'name': 'Garth Harkness McM...","[{'id': '1537335588583788544', 'name': 'Carol'...",2023-04-05 13:27:42,381
5,1252986246772559873,"{'id': '1252986246772559873', 'name': 'ingenti...","[{'id': '348598664', 'name': 'R', 'username': ...",2023-04-05 13:27:42,34
6,120400349,"{'id': '120400349', 'name': 'Javed Ahmad Tak',...","[{'id': '2534529328', 'name': 'ankur singh', '...",2023-04-05 13:27:49,847
7,994242738676789249,"{'id': '994242738676789249', 'name': 'World Ne...","[{'id': '1498550977820966914', 'name': 'Ayyapp...",2023-04-05 13:42:42,2562
8,138418838,"{'id': '138418838', 'name': 'Stigmabase | ORG'...","[{'id': '976948534053343233', 'name': 'Andre D...",2023-04-05 13:42:45,4145
9,1145266586015502336,"{'id': '1145266586015502336', 'name': 'Infecte...","[{'id': '1250020285', 'name': 'gianfra vecchio...",2023-04-05 13:42:46,921
10,132710839,"{'id': '132710839', 'name': 'Simon Fletcher', ...","[{'id': '1529696540880683009', 'name': 'PopIdl...",2023-04-05 13:42:47,508
11,843758096250036224,"{'id': '843758096250036224', 'name': 'NYZ News...","[{'id': '1366054148802772992', 'name': 'salva'...",2023-04-05 13:57:43,59
12,1595547432204410880,{},[],2023-04-05 14:27:44,0
13,1407146606323900418,"({'id': '1407146606323900418', 'name': 'Vikas ...","[{'id': '1440678523346116609', 'name': '🚩 MANO...",2023-04-05 14:27:48,6051
14,1530971264613072897,"({'id': '1530971264613072897', 'name': 'tedium...","[{'id': '1409300330358136834', 'name': '𓆨', 'u...",2023-04-05 14:27:48,23
15,1476068819655270402,"({'id': '1476068819655270402', 'name': 'Longdo...","[{'id': '2257558088', 'name': 'Atanas G. Atana...",2023-04-05 14:27:49,132
16,1602716642848690176,"({'id': '1602716642848690176', 'name': 'Louise...","[{'id': '2281916715', 'name': '𝑀𝒾𝒸𝓇𝑜𝒷𝒾𝑜𝓁𝑜𝑔𝒾𝓈𝓉 ...",2023-04-05 14:27:49,28
17,1176211661377683460,"({'id': '1176211661377683460', 'name': 'Malta ...","[{'id': '3782863666', 'name': 'Aggie Mavis Kis...",2023-04-05 14:27:50,35
18,32054188,"({'id': '32054188', 'name': 'CSL Behring', 'us...","[{'id': '930100881860767744', 'name': 'Sanofi ...",2023-04-05 14:42:50,9723
19,30846824,"({'id': '30846824', 'name': 'TOI Cities', 'use...","[{'id': '1509988203259785216', 'name': 'Sarpan...",2023-04-05 15:12:51,27862

In [22]:
df4['author_id'].nunique()

20

In [23]:
# checking the common author_id's in earlier dataset and this new df4 dataset
common_authorid = set(combined_df1['author_id']).intersection(set(df4['author_id']))

if common_tweetids:
  print(f"Commonauthorids found: {common_authorid}")

else:
  print("No common authorid;s found.")

Commonauthorids found: {1145266586015502336, 1529772772896956417, 1252986246772559873, 994242738676789249, 1638052926487756801, 843758096250036224, 57557894, 142801414, 1595547432204410880, 1407146606323900418, 1530971264613072897, 1476068819655270402, 1176211661377683460, 138418838, 1602716642848690176, 32054188, 132710839, 120400349, 30846824, 39823988}

In [24]:
final_df = pd.merge(combined_df1,df4,on = 'author_id', how = 'outer')
final_df

,tweet_id,external_twitter_id,text,author_id,created_at,lang,referenced_tweets_type,referenced_tweets_id,infos,association_tweet_id,association_scope_id,list_of_likes,date_of_collect_x,count_likes,author_info,list_of_followers,date_of_collect_y,count_followers
0,1030258,1.684841e+18,3 peaks Challenge #AxioActive💪\n\nOn the 12th ...,905089209446346752,2023-07-28 08:18:19,en,0,0,{},1030258,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1030642,1.687373e+18,3 peaks Challenge #AxioActive💪\n\nOn the 12th ...,905089209446346752,2023-08-04 08:00:00,en,0,0,{},1030642,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1030186,1.684592e+18,"Roche Drops Hemophilia A Candidate, Prepares f...",76385834,2023-07-27 15:51:10,en,0,0,{},1030186,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1014927,1.663599e+18,Pfizer’s Weekly Injection Reduced Bleeding in ...,76385834,2023-05-30 17:30:42,en,0,0,{},1014927,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,172076,1.630264e+18,"After Historic Hemophilia B Approval, uniQure ...",76385834,2023-02-27 17:51:38,en,0,0,{},172076,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29798,1620247498899230720,NaN,I've fainted in public around 4-5 times\n\n3 t...,2959298456,2023-01-31 02:28:01,en,3,1620099441326968833,{},1620247498899230720,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29799,169778,1.621986e+18,@UnitedW98762747 @manatrue @GerardO14401690 @c...,1029385925095292929,2023-02-04 21:36:31,en,2,1621981673767272453,{},169778,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29800,1621986081691279361,NaN,@UnitedW98762747 @manatrue @GerardO14401690 @c...,1029385925095292929,2023-02-04 21:36:31,en,2,1621981673767272453,{},1621986081691279361,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29801,172062,1.630293e+18,@aizaispiral I need him so bad also I think ha...,1261861179045052418,2023-02-27 19:44:59,en,2,1630186552948129793,{},172062,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29802,1630292933139202050,NaN,@aizaispiral I need him so bad also I think ha...,1261861179045052418,2023-02-27 19:44:59,en,2,1630186552948129793,{},1630292933139202050,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
final_df.isnull().sum()

tweet_id                      0
external_twitter_id       14337
text                          0
author_id                     0
created_at                    0
lang                          0
referenced_tweets_type        0
referenced_tweets_id          0
infos                         0
association_tweet_id          0
association_scope_id          0
list_of_likes             29780
date_of_collect_x         29780
count_likes               29780
author_info               28972
list_of_followers         28972
date_of_collect_y         28972
count_followers           28972
dtype: int64